services:
  app:
    build: "."
    ports:
      - "${PORT}:5173"

  done:
    depends_on:
      app:
        condition: service_started
    image: busybox:glibc
    command: >
      echo 'open http://localhost:${PORT}'
